config/routes.rb
Rails.application.routes.draw do
  

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :comments
  resources :posts
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  self.per_page = 25
  
  attr_accessor :remember_token

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Returns the hash digest of the given string.

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  
  #user.remember_token is not exposed directly!!!!
  def remember
    self.remember_token= User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :logged_in_user, only:[:edit, :update, :destroy]
  before_action :correct_user, only:[:edit, :update]
  #destroy는 correct_user 뿐만 아니라 admin도 가능해야 하므로 destroy method에서 손보는 걸로!
  before_action :user_authorized, only: [:destroy]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @posts=@user.posts.paginate(page:params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  # Before filters

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url, notice: "Invalid user") unless current_user?(@user)
  end
  
  def user_authorized
    redirect_to(users_path, notice: "Invalid user") unless (current_user == @user  || current_user.admin?)
  end                                                       
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><b>EDITING USER</b></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><b>ALL USERS</b></h1>


</br>

<% @users.each do |user| %>
  <%= link_to user.name, user %> | <%= link_to user.email,user %> | 총 글: <%= user.posts.count%>, 총 댓글: <%= user.comments.count%>
  <% unless current_user.nil? %>
    <% if current_user.admin? %>
      <% if current_user == user %>
        <%= link_to 'Edit', edit_user_path(user), id: 'only_me' %>
      <% end %>
      <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, id: 'only_me' %>
    <% elsif current_user == user %>
      <%= link_to 'Edit', edit_user_path(user), id: 'only_me' %>
      <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, id: 'only_me' %>
    <% end %>
  <% end %>
    </br>
<% end %>

<%= will_paginate class: "apple_pagination" %> 

<br>

<%= link_to 'Sign up', new_user_path %>

app/views/users/new.html.erb
<h1><b>NEW USER</b></h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


  <strong>Name:</strong>
  <%= @user.name %>
<br>
  <strong>Email:</strong>
  <%= @user.email %>
<br>
  <strong># of Posts:</strong>
  <%= @user.posts.count%>
<br>
  <strong># of Comments:</strong>
  <%= @user.comments.count%>
  <br>
  
<%= link_to 'Edit User Info', edit_user_path(@user) %>
<hr>
<%= will_paginate @posts, class: "apple_pagination" %>
<br>
<%=render @posts %>
<br>
<%= will_paginate(@posts, class: "apple_pagination")%>