config/routes.rb
Rails.application.routes.draw do
  

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :comments
  resources :posts
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope{order("created_at DESC")}
  
  has_many :comments, dependent: :destroy
  belongs_to :user
  
  self.per_page = 5
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :destroy]
  before_action :post_authorized, only: [:edit, :destroy]
  before_action :remember_location, :back
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html
      #this is for infinite scrolling.Uncommenting format.js will allow access to pagination.js.coffee and index.js.erb
      #for infinite scrolling, also add 'bootstrap-paginate' gem to the Gemfile.
      #format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new(post:@post)
    @comments= @post.comments
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
   
  #callback. 
  def post_authorized
    #This code is necessary in general.
    #But since it is already set by set_post callback for both :edit and :destroy methods
                    #(the two methods post_authorized is supposed to callback upon),
                    #this code is unnecessary in this case! Nevertheless, beware.
    #@post=Post.find(params[:id])
    redirect_to(@post, notice: "Invalid user") unless (current_user == @post.user || current_user.admin?)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%=f.hidden_field :user_id%>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, size: 70 %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%=div_for(post) do%>
  <b>Written by: <%= link_to post.user.name, post.user %></b><br/>
  <b>Written at: <%= post.created_at.strftime("%Y/%m/%d %H:%M") %></b><br/>
  <b>Title: <%= post.title %> </b><%= "("+post.comments.count.to_s+")" if post.comments.count != 0%><br/>
  <br/>
  <%= post.body.html_safe %>
  <br/>
  <%= link_to 'Show', post %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'} %>
  <hr>
<% end %>

app/views/posts/edit.html.erb
<h1><b>EDITING POST</b></h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><b>ALL POSTS</b></h1>
<br>
<div id="my-posts">
<%= render @posts %>
</div>
<br>
<div>
<%= will_paginate(@posts, class: "apple_pagination")%>
</div>

app/views/posts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1><b>NEW POST</b></h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= render @post%>

<%=form_for @comment,remote: true do |f| %>
<%=f.hidden_field :post_id%>


<p>
  <%=f.label :Comment%>
  <%=f.text_field :body%>
  <%= f.submit "Post Comment"%>
</p>
<%end%>


<div id="comments">
  <%= render @comments %>
</div>