config/routes.rb
Rails.application.routes.draw do
  

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :comments
  resources :posts
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root 'posts#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  <small>
  <% if logged_in?%>
    logged in as: <b><%=current_user.name%></b>
  <% end%>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <%= link_to "HOME", root_path, id: "logo" %>
    <%if logged_in?%>
      <%=link_to "New Post", new_post_path, id: "newpost"%>
    <%end%>
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Users", users_path%></li>
        <% if logged_in? %>
          <li><%= link_to "My posts", current_user%> </li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%=link_to "Sign up", new_user_path%></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%=favicon_link_tag 'favicon.ico'%>
<head>
  <title>대게의 고향</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header'%>
  <div class="content">
  <%= yield %>
  </div>
  <%= render 'layouts/footer'%>
  <hr>
  <div>
  <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>